import type { Actor } from "./types";

export const actors: Actor[] = [
  {
    id: "managerial-class",
    name: "Managerial progressive complex",
    short: "The coalition that treats the historic nation as the problem",
    kind: "network",
    aliases: ["permanent government", "NGO-university-HR class", "post-national centre"],
    summary:
      "Not a party and not a race. A class: the people who staff ministries, universities, PSBs, HR departments, foundations, and the Brussels industry, and whose status rests on a moral language of diversity, rights, and 'Europe' as a substitute nation. They do not need a politburo. They hire each other, grade each other, and write each other's laws. Hybrid war as they fight it is a war of position — Gramsci's phrase, which was a method, not a slur. Russia is useful to them as the named enemy that makes this file look like Kremlin disinfo.",
    interests: [
      "Keep migration, speech, and 'values' questions out of the reach of national majorities",
      "Protect a professional monopoly on moral language",
      "Treat restriction as a civilisational regression to be litigated, not a policy to be tried",
    ],
    methods: [
      "Recruitment from the same faculties",
      "Glossary work (hate, disinfo, Islamophobia) into statute",
      "Slow-walking and leaking against elected reversals",
      "Stigma as HR and as journalism",
    ],
    theaters: ["brussels", "campus", "newsroom", "legal-europe", "online"],
    domains: ["public-service", "university", "media", "lawfare", "taboo", "ngo", "supranational"],
  },
  {
    id: "european-commission",
    name: "European Commission",
    short: "Directives, funds, DSA, Pact, the values stick",
    kind: "institution",
    aliases: ["the Commission", "Berlaymont", "DGs"],
    summary:
      "A civil service with a flag. It writes the Pact on Migration and Asylum, the Digital Services Act, the Democracy Shield, anti-racism strategies, and the grant lines that feed the NGO layer which then sues member states. It is also a genuine single-market regulator. Both things are true. The hybrid question is the ratchet: competence moves up, dissent becomes 'rule of law', and a Danish restriction arrives in the building as a problem to be managed.",
    interests: [
      "More Europe in asylum, platforms, and 'values'",
      "A managed migration that never quite becomes a stop",
      "Platforms as a chokepoint for speech the building dislikes",
    ],
    methods: [
      "Regulations and directives",
      "Codes of conduct bolted onto DSA audits (hate speech +, disinfo, 2025)",
      "Funding of 'civil society' clients",
      "Infringement and conditionality",
    ],
    theaters: ["brussels", "legal-europe", "online", "mediterranean"],
    domains: ["supranational", "lawfare", "ngo", "migration", "taboo"],
  },
  {
    id: "ecthr",
    name: "European Court of Human Rights",
    short: "Articles 3 and 8 as a deportation killer; Rule 39 as a veto",
    kind: "institution",
    aliases: ["Strasbourg court", "ECtHR", "the Convention system"],
    summary:
      "A court, not a conspiracy. Its one-way reading of family life, non-refoulement, and interim measures has become a strategic weapon against elected removal policies — the UK Rwanda flight of June 2022 is the photograph. Denmark has been here too (M.A. v. Denmark on family-reunification waiting periods). Leaving the Convention is now a live political question in London and a whispered one elsewhere. That fact is the measure of the lock.",
    interests: [
      "A rights jurisprudence that treats the state's migration control as the suspect",
      "Institutional survival against 'populist' breakouts",
    ],
    methods: ["Judgments", "Rule 39 interim measures", "Pilot judgments", "Dialogue with NGOs as applicants"],
    theaters: ["legal-europe", "british-isles", "scandinavia"],
    domains: ["supranational", "lawfare", "migration"],
  },
  {
    id: "un-migration",
    name: "UN migration network",
    short: "IOM, UNHCR, OHCHR — compact, narrative, operational floor",
    kind: "institution",
    aliases: ["IOM", "UNHCR", "OHCHR", "UN Network on Migration", "Global Compact"],
    summary:
      "The Global Compact for Migration (2018) is 'non-binding' and is the first intergovernmental script for migration as a governed, permanent, positively framed condition. IOM coordinates implementation. OHCHR runs explicit 'narrative change' programmes (#StandUp4Migrants, toolboxes against 'harmful narratives'). UNHCR's protection doctrine, exported into EU law, is the legal floor under asylum volume. This is public, proud, and funded. It is also a campaign against the idea that a people may simply say no.",
    interests: [
      "Normalise migration as a structural, rights-bearing process",
      "Defeat 'harmful' (restrictionist) narratives as a programmatic goal",
      "Keep host-state enforcement inside UN-defined rails",
    ],
    methods: [
      "Soft-law compacts",
      "Operational presence at borders and in camps",
      "Narrative-change campaigns and journalist toolkits",
      "Partnership with NGOs and Commission DGs",
    ],
    theaters: ["brussels", "mediterranean", "newsroom", "online"],
    domains: ["migration", "ngo", "taboo", "supranational", "media"],
  },
  {
    id: "oic",
    name: "Organisation of Islamic Cooperation",
    short: "Defamation of religions → Islamophobia as a diplomatic weapon",
    kind: "institution",
    aliases: ["OIC", "Istanbul Process", "defamation of religions"],
    summary:
      "Fifty-seven states with a decades-long UN track: first 'defamation of religions', then HRC 16/18 and the Istanbul Process, then a permanent Islamophobia file (including a 2025 CFM resolution on Quran burnings in Sweden, Denmark, and the Netherlands). The aim is not domestic piety. It is to move European speech law toward a blasphemy standard the voters never passed. Western diplomats treated 16/18 as a compromise toward persons, not religions. The OIC treated it as unfinished business. Both readings are in the minutes.",
    interests: [
      "Shield Islam from European satire, criticism, and security talk",
      "Convert blasphemy into a human-rights language the West must honour",
      "Protect diaspora politics from 'Islamophobia' as a counter-terror tool",
    ],
    methods: [
      "UN resolutions",
      "Istanbul Process meetings",
      "Pressure after cartoon and Quran-burning crises",
      "Alliances with Western NGOs on 'hate'",
    ],
    theaters: ["legal-europe", "brussels", "scandinavia", "online"],
    domains: ["lawfare", "taboo", "islamist-entry", "supranational"],
  },
  {
    id: "muslim-brotherhood",
    name: "Muslim Brotherhood networks",
    short: "Settlement, dawa, institutions — civilisation jihad as a self-description",
    kind: "movement",
    aliases: ["Ikhwan", "CEM", "FEMYSO orbit", "Qaradawi line"],
    summary:
      "The most serious Islamist political project in Europe that is not a bomb. French, Austrian, German, and (in 2025–26) Israeli and Gulf-watch reporting describe a continent-wide lattice of federations, schools, charities, and youth orgs. The 1991 Explanatory Memorandum — settlement as a 'civilisation-jihadist process' to sabotage the Western house 'by their hands' — is a US trial exhibit, not a European command order; it is also not a forgery. Yusuf al-Qaradawi's 'conquest by dawa' is the public theology. Entryism plus natalism plus speech control is the method. A mosque is not a cell. A federation that talks like this is not just a mosque.",
    interests: [
      "Enable Islam as a civilisational alternative inside European legal space",
      "Build durable institutions and a growing observant base",
      "Make criticism of the project legally and socially expensive",
    ],
    methods: [
      "Federations, schools, halal economies, sharia councils",
      "Youth orgs as a farm system (FEMYSO and cousins)",
      "Human-rights and anti-Islamophobia dialect",
      "Party and union entry",
    ],
    theaters: ["france", "low-countries", "germany", "british-isles", "campus", "brussels"],
    domains: ["islamist-entry", "ngo", "university", "lawfare", "taboo", "street"],
  },
  {
    id: "femyso",
    name: "FEMYSO and European Brotherhood youth",
    short: "The student and youth farm system",
    kind: "network",
    parentId: "muslim-brotherhood",
    aliases: ["FEMYSO", "Forum of European Muslim Youth and Student Organisations"],
    summary:
      "French intelligence in 2025 described FEMYSO as a training platform for future Brotherhood cadres, the youth arm of the Council of European Muslims. Qatari funding since 2016 is reported in the same family of investigations. This is how a movement meets a campus. Inclusion here is not a claim that every member is an agent. It is a claim that a named pipeline exists.",
    interests: ["Cadre formation", "Respectable access to EU youth and anti-racism funds", "Campus climate"],
    methods: ["Student politics", "EU-facing advocacy", "Training camps and networks"],
    theaters: ["campus", "brussels", "france"],
    domains: ["islamist-entry", "university", "ngo", "taboo"],
  },
  {
    id: "qatar",
    name: "Qatar",
    short: "Money into campuses, Brotherhood, and Al Jazeera",
    kind: "state",
    aliases: ["Doha", "Qatar Foundation", "Al Jazeera"],
    summary:
      "A small state with a large chequebook and a spiritual-political bet on the Brotherhood. Documented gifts to European and American universities (ISGAP and others put the undeclared Anglophone total in the tens of billions; Europe is smaller and still material), funding of IESH and FEMYSO, Al Jazeera as a global frame, and a post-7 October campus climate that did not come from nowhere. This is state political warfare. It is not Russia, and it is not imaginary.",
    interests: [
      "Brotherhood as a regional tool",
      "Soft veto on how the West talks about Islam, Israel, and the Gulf",
      "Elite formation in the universities that mint diplomats",
    ],
    methods: ["University gifts", "Think-tank and student-org money", "Al Jazeera", "Hospitality and elite access"],
    theaters: ["campus", "newsroom", "british-isles", "france", "brussels"],
    domains: ["university", "media", "islamist-entry", "ngo"],
  },
  {
    id: "turkey",
    name: "Turkey / Diyanet",
    short: "Diaspora as foreign policy; imams as a civil service abroad",
    kind: "state",
    aliases: ["Ankara", "Diyanet", "Milli Görüş (cousin)", "Grey Wolves (street cousin)"],
    summary:
      "A NATO member that runs mosques, imams, and associations across Germany, the Low Countries, France, and Austria as a ministry of the interior by other means. Diyanet is a state directorate. Milli Görüş is a movement with a Turkish-Islamist grammar. The 2016–17 'Moschee-Diplomatie' rows, imam-espionage cases, and Erdoğan's campaign rallies on European soil are the file. Migration here is not only a European labour story. It is a Turkish electorate parked in the Ruhr.",
    interests: [
      "Hold the diaspora as a political resource",
      "Block European integration that would dissolve that resource",
      "Use EU accession and NATO as hostage and access",
    ],
    methods: ["Diyanet imams", "Diaspora media", "Party mobilisation from Ankara", "Intelligence among associations"],
    theaters: ["germany", "low-countries", "france", "brussels"],
    domains: ["islamist-entry", "public-service", "media", "migration"],
  },
  {
    id: "diyanet",
    name: "Diyanet",
    short: "Turkish state religious directorate in European parishes",
    kind: "service",
    parentId: "turkey",
    aliases: ["Presidency of Religious Affairs", "DITIB (German affiliate)"],
    summary:
      "The organisational edge of Ankara's European hold: salaries, sermons, and a personnel pipeline that does not answer to the host interior ministry. German DITIB rows over imam training and intelligence contacts are the public version. A state church is not inherently hybrid. A state church of another state, on your territory, preaching against your integration policy, is.",
    interests: ["Canonical and political hold on Turkish-origin Muslims", "Reporting channel home"],
    methods: ["Personnel", "Mosque construction", "Youth and women's associations"],
    theaters: ["germany", "low-countries", "france", "scandinavia"],
    domains: ["islamist-entry", "public-service"],
  },
  {
    id: "open-society",
    name: "Open Society network",
    short: "The largest private funder of the European rights-and-migration complex",
    kind: "foundation",
    aliases: ["OSF", "Soros foundations", "Open Society Foundations"],
    summary:
      "Named because the grants are named. Open Society has been a principal private funder of European litigation on migration, criminal justice, 'hate', media, and civic 'resilience' — the last of which often means resilience against the voter. George Soros as a folk devil is a different, worse file, and this atlas will not run it. A foundation that spends at continental scale on a post-national legal order is an actor. Read the grants. Do not read the memes.",
    interests: [
      "A Europe in which national majorities cannot close the door or the debate",
      "Strategic litigation as policy",
      "A civil-society layer independent of — and often hostile to — elected restriction",
    ],
    methods: ["Grants", "Litigation vehicles", "Media and university programmes", "Networked 'expert' supply"],
    theaters: ["legal-europe", "brussels", "campus", "newsroom"],
    domains: ["ngo", "lawfare", "migration", "university", "taboo"],
  },
  {
    id: "psb-complex",
    name: "Public-service broadcasters",
    short: "BBC, DR, SVT, NRK, ARD/ZDF, France Télévisions, RTÉ",
    kind: "media",
    aliases: ["PSB", "licence-fee broadcasters", "public service media"],
    summary:
      "The most important media actors in northern Europe because they are the ones a voter cannot switch off without a political fight. Their charters say inform, educate, entertain, and hold power to account. Their recruitment says the same universities as the ministry. Bias studies, ombudsman rows, and the 2015–24 migration file (who was interviewed, which numbers were 'context') are the open record. A PSB is not a party channel. It is a weather system.",
    interests: [
      "Protect the licence-fee or state-grant bargain",
      "Remain the moral centre against 'polarisation'",
      "Treat restrictionist politics as a problem to be explained, not a public to be served",
    ],
    methods: ["Running order", "Style guides", "Expert rolodex", "Internal values regimes", "Crisis liturgy after attacks"],
    theaters: ["newsroom", "scandinavia", "british-isles", "germany", "france"],
    domains: ["media", "public-service", "taboo"],
  },
  {
    id: "university-admin",
    name: "University administrative complex",
    short: "DEI offices, speech codes, the factory for the next ministry",
    kind: "institution",
    aliases: ["campus DEI", "equity offices", "the administration"],
    summary:
      "The power on campus is not the famous professor. It is the office that signs off hiring, events, research ethics, and student discipline. That office speaks a language imported from US HR and postcolonial curriculum, then exported into European civil services by the people it mints. Foreign gifts (Qatar and others) buy programmes; the administration buys peace. After 7 October 2023 the product was visible in the quad.",
    interests: ["Administrative growth", "Risk-off peace with activist students", "A moral monopoly on 'inclusion'"],
    methods: ["Speech codes", "Hiring filters", "Event vetoes", "Bias-response teams", "Partnership with student Islamist and identitarian orgs"],
    theaters: ["campus", "british-isles", "france", "germany"],
    domains: ["university", "taboo", "islamist-entry"],
  },
  {
    id: "ngo-litigation",
    name: "Litigation and reception NGOs",
    short: "ECRE, legal-aid shops, SAR NGOs, the second civil service",
    kind: "network",
    aliases: ["ECRE orbit", "SAR NGOs", "strategic litigation", "refugee industrial complex"],
    summary:
      "A market and a priesthood. Reception contractors are paid per arrival. Legal-aid NGOs are paid to sue the state that also funds them. Search-and-rescue NGOs create a wet corridor whose existence is then cited as proof that the corridor cannot be closed. ECRE and cousins coordinate the legal line across capitals. This is not 'civil society' as a check. It is an operational layer with a business model.",
    interests: ["Volume, because volume is budget and meaning", "A legal order in which enforcement looks like a violation", "Moral standing against elected restriction"],
    methods: ["Boats and buses", "Strasbourg applications", "Media packaging", "Commission and foundation grants"],
    theaters: ["mediterranean", "legal-europe", "brussels", "newsroom"],
    domains: ["ngo", "migration", "lawfare", "media"],
  },
  {
    id: "islamist-street",
    name: "Islamist street and clan enforcement",
    short: "The extra-legal blasphemy law and the no-go fact",
    kind: "movement",
    aliases: ["Salafi milieus", "clan networks", "grooming-gang pattern", "banlieue street"],
    summary:
      "Not a single organisation. A recurring capability: punish cartoonists and teachers, police women, run sexual-exploitation networks that officials were afraid to name, and raise the price of ordinary policing until the state bargains. Van Gogh, Hebdo, Paty, the 2023 riots, Rotherham and its sister files, Swedish bombings — different men, same lesson. The hybrid use is downstream: each episode trains the PSB and the ministry to talk about cohesion rather than the enabling settlement.",
    interests: ["Impunity in territory", "Blasphemy enforcement", "Status inside the parallel society"],
    methods: ["Riot", "Targeted killing and threats", "Grooming and clan crime", "Communal bloc as political shield"],
    theaters: ["france", "british-isles", "scandinavia", "low-countries", "germany"],
    domains: ["street", "islamist-entry", "taboo"],
  },
  {
    id: "salafi-milieu",
    name: "European Salafi milieu",
    short: "Quietist on the brochure, a travel bureau in the kitchen",
    kind: "movement",
    aliases: ["Salafi networks", "Grimhøj orbit", "Maskinhuset cousins", "purist-jihadist pipeline"],
    summary:
      "Not a party and not every bearded room. A current: scriptural purism that isolates the flock from the demos, then — in the jihadi fork — sells the camp. Grimhøj in Aarhus is the Danish photograph: an ice factory that police tied to about a fifth of the country's Syria travellers. The minbar denies. The travel did not. French, Austrian, and German services will say 'Salafi' in public. Denmark still prefers 'radicalisation' as a social-work noun. The hybrid use is the pool: a sacral network that can be a parish on Friday and a recruitment shop on Tuesday without changing the lock.",
    interests: [
      "A flock that answers to a transnational ummah before a Danish demos",
      "A pipeline to theatres — Syria yesterday, wherever the brand is tomorrow",
      "Impunity for the room: deny the minbar, keep the kitchen",
    ],
    methods: ["Study circles", "Isolation and takfir-lite", "Encrypted flyers", "Mosque-adjacent travel bureaux", "Veteran prestige"],
    theaters: ["scandinavia", "france", "germany", "low-countries", "british-isles", "online"],
    domains: ["islamist-entry", "street", "taboo"],
  },
  {
    id: "hizb-ut-tahrir",
    name: "Hizb ut-Tahrir",
    short: "Open caliphate politics from a legal Danish mosque",
    kind: "movement",
    aliases: ["HuT", "Masjid al-Faruq", "Liberation Party"],
    summary:
      "A transnational Islamist party that wants a caliphate and will say so on a Copenhagen pavement. Germany has banned it. Denmark has not. Kühle's 2017 mapping put Masjid al-Faruq in the mixed nine and named it as Hizb ut-Tahrir's mosque. That is a documented room, not a vibe. The hybrid use is legality as cover: a party the security services watch, preaching reconstitution of a political order the Folketing is not allowed to call an enemy without a new crime being written against the naming.",
    interests: [
      "A caliphate as a political programme, not a metaphor",
      "Keep the Danish room legal while the German one is not",
      "Turn any restriction into a free-speech martyrdom",
    ],
    methods: ["Public rallies", "Literature", "A named mosque", "Campus and youth circles"],
    theaters: ["scandinavia", "british-isles", "germany", "online"],
    domains: ["islamist-entry", "taboo", "street"],
  },
  {
    id: "russia",
    name: "Russian Federation",
    short: "A real grey-zone attacker — and a parasite on this file, not its author",
    kind: "state",
    aliases: ["Moscow", "the Kremlin", "RT / FIMI"],
    summary:
      "The last atlas made Russia the principal. That was the primitive definition: cables, GRU arson, Belarusian border stunts, firehose media. Those campaigns exist. They are not the campaign that rewrote Malmö, Molenbeek, Rotherham, or the DSA. Moscow's interest here is opportunistic — amplify the fracture, sell 'decadent West', run the occasional border trick. Treating this interior war as a Russian op is itself a move in the taboo domain. Inclusion is to keep the parasite on the page, not on the throne.",
    interests: [
      "European fracture as a strategic good",
      "Migration as a FIMI theme and, at the Finnish/Norwegian fence, as a tool",
      "Redirecting Western security energy toward NATO theatre and away from interior reconstruction",
    ],
    methods: ["FIMI", "Border instrumentalisation with Belarus", "Occasional cultivation of both identitarian and anti-racist useful voices"],
    theaters: ["online", "scandinavia", "newsroom"],
    domains: ["taboo", "media", "migration"],
  },
  {
    id: "denmark-state",
    name: "Danish restrictionist turn",
    short: "The European proof that policy, not weather, sets the numbers",
    kind: "state",
    aliases: ["paradigm shift", "ghetto / parallel-society laws", "Danish Social Democrats after 2019"],
    summary:
      "Not an enemy of this atlas — a control case. From 2015–19 Denmark moved, under first a centre-right and then a Social Democratic government, to a 'paradigm shift': temporary protection, return, jewellery-law theatre, ghetto/parallel-society legislation, a hard line on Syrian withdrawals, and a public argument that the welfare state is the victim of volume. Courts and UN bodies have fought pieces of it. The numbers moved. That is why the country is hated in the NGO layer and studied everywhere else.",
    interests: [
      "A welfare state that remains a welfare state",
      "Return as the default, not integration-as-euphemism",
      "A public language in which the problem may be named",
    ],
    methods: ["Statute", "Ghetto/parallel-society packages", "Diplomatic fights in Strasbourg and Geneva", "Social-democratic conversion as political cover"],
    theaters: ["scandinavia", "legal-europe", "brussels"],
    domains: ["migration", "lawfare", "public-service", "supranational"],
  },
  {
    id: "pet-fe",
    name: "PET and FE",
    short: "Danish intelligence: the shop that mapped the Syria pipeline, then lost the right to stay silent",
    kind: "institution",
    aliases: ["Politiets Efterretningstjeneste", "Forsvarets Efterretningstjeneste", "Danish intelligence community"],
    summary:
      "A small state's eyes. PET does the interior: terrorism, extremism, counter-intelligence. FE does the exterior: foreign fighters, partner services, the cable. They recruited Ahmed Samsam, paid him, sent him into Syria in 2013–14, then neither-confirmed-nor-denied him into an eight-year Spanish terror conviction. The Supreme Court in September 2025 made them say the source relationship out loud. Inclusion here is not a verdict that the services are the enemy. It is the record of a HUMINT collapse in the one European control case that otherwise moved the numbers.",
    interests: [
      "Keep source relationships off the public record",
      "Map Danish travellers into jihadi groups without burning the mapper",
      "Survive oversight, courts, and a press that treats silence as the scandal",
    ],
    methods: [
      "Human sources paid in cash and kit",
      "Neither-confirm-nor-deny as doctrine",
      "Service-to-service notes that never become courtroom evidence",
      "Compensation talks in a closed room while the public line is silence",
    ],
    theaters: ["scandinavia", "legal-europe", "newsroom"],
    domains: ["islamist-entry", "lawfare", "taboo", "public-service", "street"],
  },
];

export const actorById = Object.fromEntries(actors.map((a) => [a.id, a])) as Record<string, Actor>;
