import type { TimelineEvent } from "./types";

export const timeline: TimelineEvent[] = [
  {
    id: "t-1968",
    date: "1968",
    title: "The long march names itself",
    attribution: "confirmed",
    domainId: "university",
    theaterId: "campus",
    note: "New Left intellectuals describe capture of school, press, and administration as the work. A method, not a slur. The factory opens.",
  },
  {
    id: "t-1991-memo",
    date: "1991-05",
    title: "Brotherhood Explanatory Memorandum",
    campaignId: "brotherhood-settlement",
    domainId: "islamist-entry",
    attribution: "high",
    note: "Settlement as a 'civilisation-jihadist process.' US trial exhibit, not a European order — and not a forgery.",
  },
  {
    id: "t-1999-oic",
    date: "1999",
    title: "OIC 'defamation of religions' track begins in earnest",
    campaignId: "oic-islamophobia",
    domainId: "lawfare",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Blasphemy looking for a human-rights costume.",
  },
  {
    id: "t-2004-vangogh",
    date: "2004-11-02",
    title: "Theo van Gogh murdered in Amsterdam",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "low-countries",
    attribution: "confirmed",
    note: "The filmmaker as target. Fortuyn already dead. Early warning punished.",
  },
  {
    id: "t-2005-cartoons",
    date: "2005-09",
    title: "Jyllands-Posten cartoons",
    campaignId: "oic-islamophobia",
    domainId: "taboo",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "A Danish press story becomes a diplomatic system. The teaching case.",
  },
  {
    id: "t-2005-banlieue",
    date: "2005-10",
    title: "French banlieue riots",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "france",
    attribution: "high",
    note: "The street tariff on ordinary policing, already a landscape.",
  },
  {
    id: "t-2011-istanbul",
    date: "2011-07",
    title: "Istanbul Process launched",
    campaignId: "oic-islamophobia",
    domainId: "supranational",
    attribution: "confirmed",
    note: "HRC 16/18 implementation. Western diplomats think they compromised. The OIC is not finished.",
  },
  {
    id: "t-2011-breivik",
    date: "2011-07-22",
    title: "Utøya and Oslo — the taboo's kill-switch",
    campaignId: "taboo-naming",
    domainId: "taboo",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "A monster who cited replacement. He does not own fertility rates. The taboo keeps him on the desk anyway.",
  },
  {
    id: "t-2014-rotherham",
    date: "2014-08",
    title: "Jay report on Rotherham",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "british-isles",
    attribution: "confirmed",
    note: "Official cowardice with a racial taboo at the centre. The bill was girls.",
  },
  {
    id: "t-2015-hebdo",
    date: "2015-01-07",
    title: "Charlie Hebdo",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "france",
    attribution: "confirmed",
    note: "The newsroom as target. Cohesion liturgy against a civilisational fact.",
  },
  {
    id: "t-2015-merkel",
    date: "2015-09",
    title: "Merkel's Öffnung",
    campaignId: "mass-settlement",
    domainId: "migration",
    theaterId: "germany",
    attribution: "confirmed",
    note: "The largest single elite decision in the interior war. Not a weather event.",
  },
  {
    id: "t-2015-bataclan",
    date: "2015-11-13",
    title: "Bataclan and the 13 November attacks",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "france",
    attribution: "confirmed",
    note: "The concert hall. Not a speech crime — the climate in which speech crimes are then written.",
  },
  {
    id: "t-2015-cologne",
    date: "2015-12-31",
    title: "Cologne New Year",
    campaignId: "psb-monopoly",
    domainId: "media",
    theaterId: "germany",
    attribution: "high",
    note: "Crime plus a style-guide crisis. Origin as the unsayable.",
  },
  {
    id: "t-2016-hatecode",
    date: "2016",
    title: "EU Code of Conduct on illegal hate speech",
    campaignId: "counter-legislation",
    domainId: "lawfare",
    theaterId: "brussels",
    attribution: "confirmed",
    note: "The voluntary seed of the later DSA machine.",
  },
  {
    id: "t-2018-gcm",
    date: "2018-12-19",
    title: "Global Compact for Migration adopted",
    campaignId: "global-compact",
    domainId: "migration",
    attribution: "confirmed",
    note: "Non-binding, and a script. Narrative-change bureaucracies take it from here.",
  },
  {
    id: "t-2019-denmark",
    date: "2019",
    title: "Danish paradigm shift under the Social Democrats",
    campaignId: "denmark-reversal",
    domainId: "migration",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "The control case: convert the party that owns the building.",
  },
  {
    id: "t-2020-paty",
    date: "2020-10-16",
    title: "Samuel Paty beheaded",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "france",
    attribution: "confirmed",
    note: "The school as target. The campaign against the teacher, completed.",
  },
  {
    id: "t-2021-scotland",
    date: "2021-04",
    title: "Scotland Hate Crime Act",
    campaignId: "counter-legislation",
    domainId: "lawfare",
    theaterId: "british-isles",
    attribution: "confirmed",
    note: "Stirring-up offences expanded. The bizarre recursion, in statute.",
  },
  {
    id: "t-2021-ma-denmark",
    date: "2021",
    title: "M.A. v. Denmark — family-reunion waiting periods",
    campaignId: "ecthr-lock",
    domainId: "supranational",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Strasbourg against the control case.",
  },
  {
    id: "t-2022-rwanda",
    date: "2022-06-14",
    title: "ECtHR Rule 39 empties the first Rwanda flight",
    campaignId: "ecthr-lock",
    domainId: "supranational",
    theaterId: "british-isles",
    attribution: "confirmed",
    note: "The photograph of the lock. Not the EU. The Convention.",
  },
  {
    id: "t-2023-nahel",
    date: "2023-06",
    title: "Nahel riots in France",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "france",
    attribution: "high",
    note: "A week of burned France as a political tariff.",
  },
  {
    id: "t-2023-oct7-campus",
    date: "2023-10",
    title: "Campus after 7 October",
    campaignId: "university-capture",
    domainId: "university",
    theaterId: "campus",
    attribution: "high",
    note: "The factory's product, on display. Qatar, Brotherhood youth, administration — one production line.",
  },
  {
    id: "t-2024-dsa",
    date: "2024-02",
    title: "Digital Services Act fully applicable",
    campaignId: "dsa-speech",
    domainId: "lawfare",
    theaterId: "online",
    attribution: "confirmed",
    note: "The new chokepoint, live.",
  },
  {
    id: "t-2024-twotier",
    date: "2024-08",
    title: "UK two-tier becomes a household phrase",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "british-isles",
    attribution: "high",
    note: "Southport riots and charging optics. Mass perception as a strategic fact.",
  },
  {
    id: "t-2025-codes",
    date: "2025-02",
    title: "Hate-speech and disinfo codes bolted onto the DSA",
    campaignId: "dsa-speech",
    domainId: "lawfare",
    theaterId: "brussels",
    attribution: "confirmed",
    note: "Voluntary, then auditable. Platforms as a continental speech handle.",
  },
  {
    id: "t-2025-oic",
    date: "2025-06",
    title: "OIC CFM still seized of Scandinavian Quran burnings",
    campaignId: "oic-islamophobia",
    domainId: "lawfare",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Istanbul Process to be 'revigorated.' Small states, long memory, ongoing file.",
  },
  {
    id: "t-2026-hubs",
    date: "2026-08",
    title: "Danish-led return-hub diplomacy in Kigali",
    campaignId: "denmark-reversal",
    domainId: "migration",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Denmark, Germany, Austria, Greece, Netherlands. The workaround, exported — and already a lawfare target.",
  },
  {
    id: "t-1967-nusrat",
    date: "1967-07-21",
    title: "First purpose-built mosque in the Nordic region",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Nusrat Jahan, Hvidovre. Ahmadiyya. The papers were curious. The Folketing was not.",
  },
  {
    id: "t-1974-sunni",
    date: "1974",
    title: "One Sunni mosque in living memory",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "high",
    note: "The control year. Guest-worker rooms just beginning. Ahmadiyya declared outside Islam the same year.",
  },
  {
    id: "t-2006-kuehle",
    date: "2006",
    title: "First national mosque mapping: ~115",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Kühle's walk-in. 104 Sunni, 10 Shia, 1 Ahmadiyya. The mapped layer gets a number.",
  },
  {
    id: "t-2012-emir",
    date: "2012-11",
    title: "Danish emir videos sell the Syria camp",
    campaignId: "syria-pipeline",
    domainId: "islamist-entry",
    theaterId: "online",
    attribution: "confirmed",
    note: "The war becomes a domestic youth product. The advertisement is aggressive.",
  },
  {
    id: "t-2014-hbku",
    date: "2014-06",
    title: "Qatar's grand mosque opens on Rovsingsgade",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Hamad Bin Khalifa Civilisation Center. The purpose-built layer gets its photograph. A foreign parish in the capital.",
  },
  {
    id: "t-2014-grimhoj",
    date: "2014",
    title: "Grimhøj named as a travel bureau",
    campaignId: "syria-pipeline",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Police: about a fifth of Danish Syria travellers. The ice factory as shop window.",
  },
  {
    id: "t-2015-imam-ali",
    date: "2015",
    title: "Imam Ali Mosque opens on Vibevej",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Iranian parish. The Folketing later finds it cannot dissolve the room.",
  },
  {
    id: "t-2016-pet135",
    date: "2016-04",
    title: "PET: 135+ Danish travellers to Syria/Iraq",
    campaignId: "syria-pipeline",
    domainId: "street",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Among the highest per-capita rates in the EU. The pipeline is no longer deniable.",
  },
  {
    id: "t-2017-kuehle2",
    date: "2017-12",
    title: "Mapped mosques ~170, +48% in eleven years",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Kühle & Larsen. ~40% transnational. At least ten uncertified. The dark figure begins to speak.",
  },
  {
    id: "t-2025-hidayyah",
    date: "2026-03",
    title: "Blood-money mosque keeps recognition",
    campaignId: "mosque-census",
    domainId: "street",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Al-Hidayyah: arbitration for clan killings, then no sanction. A hostile room as a rights-holder.",
  },
  {
    id: "t-2012-samsam",
    date: "2012",
    title: "PET recruits Ahmed Samsam as a paid Syria source",
    campaignId: "samsam-case",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Gang past, Syrian origin, Danish passport. The shop's way into a pipeline it cannot walk itself.",
  },
  {
    id: "t-2017-samsam-spain",
    date: "2017-06",
    title: "Samsam arrested in Spain — Copenhagen's line is silence",
    campaignId: "samsam-case",
    domainId: "lawfare",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Neither confirm nor deny. Spain convicts him in 2018 of joining Islamic State. Eight years.",
  },
  {
    id: "t-2021-samsam-memo",
    date: "2021-06",
    title: "Leaked PET note: serious failure, exceptional access, no rescue",
    campaignId: "samsam-case",
    domainId: "taboo",
    theaterId: "newsroom",
    attribution: "high",
    note: "The service's own paper. Compensation talked. He is still in a cell.",
  },
  {
    id: "t-2021-findsen-sweep",
    date: "2021-12-08",
    title: "PET arrests the FE chief and Samsam's handler in one sweep",
    campaignId: "samsam-case",
    domainId: "public-service",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Intelligence at war with itself. The Samsam leak is one of the strands. Findsen's charges later collapse.",
  },
  {
    id: "t-2025-samsam-sc",
    date: "2025-09-02",
    title: "Supreme Court forces PET and FE to acknowledge Samsam",
    campaignId: "samsam-case",
    domainId: "lawfare",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Seven judges, unanimous. Joint statement the same afternoon. NCND yields. Every future source can read it.",
  },
  {
    id: "t-2018-medieaftale",
    date: "2018-06",
    title: "VLAK/DF medieaftale tries to constrain DR",
    campaignId: "medieforlig-neutrality",
    domainId: "public-service",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "20% cut, no long web articles. The last right-hand constraint. Reversed within a year as 'armslængde.'",
  },
  {
    id: "t-2023-medieaftale",
    date: "2023-06-14",
    title: "Medieaftale 2023–26: pluralism becomes the targeted duty",
    campaignId: "medieforlig-neutrality",
    domainId: "media",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "'Alsidighed og pluralisme' as a task. 'Upartisk' stays as a sentence. Diversity becomes countable.",
  },
  {
    id: "t-2026-medieprogram",
    date: "2026-06",
    title: "S–SF–RV–M programme: slim DR's frame, do not audit its politics",
    campaignId: "medieforlig-neutrality",
    domainId: "public-service",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Afbureaukratisering as the working title. The 2025 slagside offer is not in the programme.",
  },
];
