import type { Actor } from "./types";

export const actors: Actor[] = [
  {
    id: "managerial-class",
    name: "Det managerielt-progressive kompleks",
    short: "Koalitionen, der behandler den historiske nation som problemet",
    kind: "network",
    aliases: ["det permanente styre", "NGO-universitet-HR-klassen", "det postnationale centrum"],
    summary:
      "Ikke et parti og ikke en race. En klasse: de mennesker, der bemander ministerier, universiteter, public service, HR-afdelinger, fonde og Bruxelles-industrien, og hvis status hviler på et moralsk sprog om diversitet, rettigheder og 'Europa' som erstatningsnation. De har ikke brug for et politbureau. De ansætter hinanden, bedømmer hinanden og skriver hinandens love. Hybridkrig, som de fører den, er stillingskrig — Gramscis frase, som var en metode, ikke et skældsord. Rusland er nyttig for dem som den navngivne fjende, der får denne fil til at se ud som kreml-desinfo.",
    interests: [
      "Holde migrations-, tale- og 'værdier'-spørgsmål uden for nationale flertals rækkevidde",
      "Beskytte et professionelt monopol på moralsk sprog",
      "Behandle begrænsning som civilisatorisk regression, der skal litigieres, ikke en politik, der skal prøves",
    ],
    methods: [
      "Rekruttering fra de samme fakulteter",
      "Ordbogsarbejde (had, desinfo, islamofobi) ind i lov",
      "Slæb og læk mod valgte tilbageførsler",
      "Stigma som HR og som journalistik",
    ],
    theaters: ["brussels", "campus", "newsroom", "legal-europe", "online"],
    domains: ["public-service", "university", "media", "lawfare", "taboo", "ngo", "supranational"],
  },
  {
    id: "european-commission",
    name: "Europa-Kommissionen",
    short: "Direktiver, fonde, DSA, pagten, værdistokken",
    kind: "institution",
    aliases: ["Kommissionen", "Berlaymont", "DG'er"],
    summary:
      "Et embedsværk med et flag. Den skriver pagten om migration og asyl, Digital Services Act, Democracy Shield, antiracismestrategier og de tilskudslinjer, der fodrer NGO-laget, som så sagsøger medlemsstater. Den er også en ægte indre-marked-regulator. Begge ting er sande. Hybridspørgsmålet er skralden: kompetence flytter op, dissent bliver 'retsstat', og en dansk stramning ankommer i bygningen som et problem, der skal styres.",
    interests: [
      "Mere Europa i asyl, platforme og 'værdier'",
      "En styret migration, der aldrig rigtig bliver et stop",
      "Platforme som knudepunkt for tale, bygningen ikke kan lide",
    ],
    methods: [
      "Forordninger og direktiver",
      "Adfærdskodeks boltet på DSA-revisioner (hadtale +, desinfo, 2025)",
      "Finansiering af 'civilsamfunds'-klienter",
      "Traktatbrud og konditionalitet",
    ],
    theaters: ["brussels", "legal-europe", "online", "mediterranean"],
    domains: ["supranational", "lawfare", "ngo", "migration", "taboo"],
  },
  {
    id: "ecthr",
    name: "Den Europæiske Menneskerettighedsdomstol",
    short: "Artikel 3 og 8 som udsendelsesdræber; regel 39 som veto",
    kind: "institution",
    aliases: ["Strasbourg-domstolen", "EMD", "konventionssystemet"],
    summary:
      "En domstol, ikke en sammensværgelse. Dens ensrettede læsning af familieliv, non-refoulement og midlertidige foranstaltninger er blevet et strategisk våben mod valgte udsendelsespolitikker — den britiske Rwanda-flyvning i juni 2022 er fotografiet. Danmark har også været her (M.A. mod Danmark om ventetider for familiesammenføring). At forlade konventionen er nu et levende politisk spørgsmål i London og et hvisket ét andre steder. Den kendsgerning er målet for låsen.",
    interests: [
      "En rettighedsjurisprudens, der behandler statens migrationskontrol som den mistænkte",
      "Institutionel overlevelse mod 'populistiske' udbrud",
    ],
    methods: ["Domme", "Regel 39 midlertidige foranstaltninger", "Pilotdomme", "Dialog med NGO'er som sagsøgere"],
    theaters: ["legal-europe", "british-isles", "scandinavia"],
    domains: ["supranational", "lawfare", "migration"],
  },
  {
    id: "un-migration",
    name: "FN's migrationsnetværk",
    short: "IOM, UNHCR, OHCHR — kompakt, narrativ, operationelt gulv",
    kind: "institution",
    aliases: ["IOM", "UNHCR", "OHCHR", "UN Network on Migration", "Global Compact"],
    summary:
      "Den globale kompakt for migration (2018) er 'ikke-bindende' og er det første mellemstatslige script for migration som en styret, permanent, positivt framed tilstand. IOM koordinerer implementering. OHCHR kører eksplicitte 'narrativ forandring'-programmer (#StandUp4Migrants, værktøjskasser mod 'skadelige narrativer'). UNHCR's beskyttelsesdoktrin, eksporteret ind i EU-lov, er det juridiske gulv under asylvolumen. Dette er offentligt, stolt og finansieret. Det er også en kampagne mod ideen om, at et folk simpelthen må sige nej.",
    interests: [
      "Normalisere migration som en strukturel, rettighedsbærende proces",
      "Nedkæmpe 'skadelige' (restriktive) narrativer som et programmatisk mål",
      "Holde værtsstatens håndhævelse inden for FN-definerede skinner",
    ],
    methods: [
      "Blød-lov-kompakter",
      "Operationel tilstedeværelse ved grænser og i lejre",
      "Narrativ-forandring-kampagner og journalistværktøjskasser",
      "Partnerskab med NGO'er og kommissions-DG'er",
    ],
    theaters: ["brussels", "mediterranean", "newsroom", "online"],
    domains: ["migration", "ngo", "taboo", "supranational", "media"],
  },
  {
    id: "oic",
    name: "Organisationen for Islamisk Samarbejde",
    short: "Religiøs bagtalelse → islamofobi som diplomatisk våben",
    kind: "institution",
    aliases: ["OIC", "Istanbul-processen", "defamation of religions"],
    summary:
      "Syvoghalvtreds stater med et årtier langt FN-spor: først 'religiøs bagtalelse', så HRC 16/18 og Istanbul-processen, så en permanent islamofobisag (inklusive en CFM-resolution i 2025 om koranafbrændinger i Sverige, Danmark og Nederlandene). Målet er ikke indenlandsk fromhed. Det er at flytte europæisk talelov mod en blasfemistandard, vælgerne aldrig vedtog. Vestlige diplomater behandlede 16/18 som et kompromis hen imod personer, ikke religioner. OIC behandlede det som uafsluttet forretning. Begge læsninger står i referaterne.",
    interests: [
      "Skærme islam mod europæisk satire, kritik og sikkerhedssnak",
      "Konvertere blasfemi til et menneskerettighedssprog, Vesten skal ære",
      "Beskytte diasporapolitik mod 'islamofobi' som kontraterrorværktøj",
    ],
    methods: [
      "FN-resolutioner",
      "Istanbul-proces-møder",
      "Pres efter tegne- og koranafbrændingskriser",
      "Alliancer med vestlige NGO'er om 'had'",
    ],
    theaters: ["legal-europe", "brussels", "scandinavia", "online"],
    domains: ["lawfare", "taboo", "islamist-entry", "supranational"],
  },
  {
    id: "muslim-brotherhood",
    name: "Det Muslimske Broderskabs netværk",
    short: "Bosættelse, dawa, institutioner — civilisationsjihad som selvbeskrivelse",
    kind: "movement",
    aliases: ["Ikhwan", "CEM", "FEMYSO-kredsen", "Qaradawi-linjen"],
    summary:
      "Det alvorligste islamistiske politiske projekt i Europa, der ikke er en bombe. Fransk, østrigsk, tysk og (i 2025–26) israelsk og golf-overvågningsrapportering beskriver et kontinentspændende gitter af forbund, skoler, velgørenhed og ungdomsorganisationer. 1991-forklaringsmemorandummet — bosættelse som en 'civilisations-jihadistisk proces' for at sabotere det vestlige hus 'med deres egne hænder' — er et amerikansk retssagsbilag, ikke en europæisk kommandordre; det er heller ikke en forfalskning. Yusuf al-Qaradawis 'erobring ved dawa' er den offentlige teologi. Indtrængen plus natalisme plus talekontrol er metoden. En moske er ikke en celle. Et forbund, der taler sådan, er ikke bare en moske.",
    interests: [
      "Gøre islam til et civilisatorisk alternativ inde i europæisk retligt rum",
      "Bygge holdbare institutioner og en voksende observant base",
      "Gøre kritik af projektet juridisk og socialt dyrt",
    ],
    methods: [
      "Forbund, skoler, halal-økonomier, sharia-råd",
      "Ungdomsorganisationer som farmsystem (FEMYSO og fætre)",
      "Menneskerettigheds- og anti-islamofobi-dialekt",
      "Parti- og fagforeningsindtrængen",
    ],
    theaters: ["france", "low-countries", "germany", "british-isles", "campus", "brussels"],
    domains: ["islamist-entry", "ngo", "university", "lawfare", "taboo", "street"],
  },
  {
    id: "femyso",
    name: "FEMYSO og Broderskabets europæiske ungdom",
    short: "Studenter- og ungdoms-farmsystemet",
    kind: "network",
    parentId: "muslim-brotherhood",
    aliases: ["FEMYSO", "Forum of European Muslim Youth and Student Organisations"],
    summary:
      "Fransk efterretning beskrev i 2025 FEMYSO som en træningsplatform for fremtidige broderskabskadrer, ungdomsarmen af Council of European Muslims. Qatari-finansiering siden 2016 rapporteres i den samme familie af undersøgelser. Sådan møder en bevægelse et campus. Optagelse her er ikke et krav om, at hvert medlem er agent. Det er et krav om, at en navngivet rørledning findes.",
    interests: ["Kadrerformering", "respektabel adgang til EU's ungdoms- og antiracismemidler", "Campusklima"],
    methods: ["Studenterpolitik", "EU-vendt advocacy", "Træningslejre og netværk"],
    theaters: ["campus", "brussels", "france"],
    domains: ["islamist-entry", "university", "ngo", "taboo"],
  },
  {
    id: "qatar",
    name: "Qatar",
    short: "Penge ind i campusser, Broderskabet og Al Jazeera",
    kind: "state",
    aliases: ["Doha", "Qatar Foundation", "Al Jazeera"],
    summary:
      "En lille stat med en stor checkhæfte og et åndeligt-politisk væddemål på Broderskabet. Dokumenterede gaver til europæiske og amerikanske universiteter (ISGAP og andre sætter det udeklarerede anglosaksiske total i titusindvis af milliarder; Europa er mindre og stadig materielt), finansiering af IESH og FEMYSO, Al Jazeera som global ramme, og et post-7. oktober-campusklima, der ikke kom ud af ingenting. Dette er statslig politisk krigsførelse. Det er ikke Rusland, og det er ikke indbildt.",
    interests: [
      "Broderskabet som regionalt værktøj",
      "Blødt veto over, hvordan Vesten taler om islam, Israel og Golfen",
      "Eliteformering på de universiteter, der mønter diplomater",
    ],
    methods: ["Universitetsgaver", "Tænketanks- og studenterorganisationspenge", "Al Jazeera", "Gæstfrihed og eliteadgang"],
    theaters: ["campus", "newsroom", "british-isles", "france", "brussels"],
    domains: ["university", "media", "islamist-entry", "ngo"],
  },
  {
    id: "turkey",
    name: "Tyrkiet / Diyanet",
    short: "Diaspora som udenrigspolitik; imamer som et embedsværk i udlandet",
    kind: "state",
    aliases: ["Ankara", "Diyanet", "Milli Görüş (fætter)", "De grå ulve (gadefætter)"],
    summary:
      "Et NATO-medlem, der kører moskeer, imamer og foreninger på tværs af Tyskland, Lavlandene, Frankrig og Østrig som et indenrigsministerium med andre midler. Diyanet er et statsdirektorat. Milli Görüş er en bevægelse med en tyrkisk-islamistisk grammatik. 2016–17-'Moschee-Diplomatie'-rækkerne, imam-spionagesager og Erdoğans valgkampagner på europæisk jord er filen. Migration her er ikke kun en europæisk arbejdshistorie. Det er et tyrkisk vælgerkorps parkeret i Ruhr.",
    interests: [
      "Holde diasporaen som en politisk ressource",
      "Blokere europæisk integration, der ville opløse den ressource",
      "Bruge EU-optagelse og NATO som gidsel og adgang",
    ],
    methods: ["Diyanet-imamer", "Diasporamedier", "Partimobilisering fra Ankara", "Efterretning blandt foreninger"],
    theaters: ["germany", "low-countries", "france", "brussels"],
    domains: ["islamist-entry", "public-service", "media", "migration"],
  },
  {
    id: "diyanet",
    name: "Diyanet",
    short: "Tyrkisk statsreligiøst direktorat i europæiske sogne",
    kind: "service",
    parentId: "turkey",
    aliases: ["Direktoratet for religiøse anliggender", "DITIB (tysk affiliate)"],
    summary:
      "Den organisatoriske kant af Ankaras europæiske tag: lønninger, prædikener og en personalerørledning, der ikke svarer til værtslandets indenrigsministerium. Tyske DITIB-rækker om imamuddannelse og efterretningskontakter er den offentlige version. En statskirke er ikke i sig selv hybrid. En statskirke fra en anden stat, på dit territorium, der prædiker imod din integrationspolitik, er.",
    interests: ["Kanonisk og politisk tag på muslimer af tyrkisk oprindelse", "Rapporteringskanal hjem"],
    methods: ["Personale", "Moskebyggeri", "Ungdoms- og kvindeforeninger"],
    theaters: ["germany", "low-countries", "france", "scandinavia"],
    domains: ["islamist-entry", "public-service"],
  },
  {
    id: "open-society",
    name: "Open Society-netværket",
    short: "Den største private donor til det europæiske rettigheds- og migrationskompleks",
    kind: "foundation",
    aliases: ["OSF", "Soros-fondene", "Open Society Foundations"],
    summary:
      "Navngivet, fordi tilskuddene er navngivne. Open Society har været en principal privat donor til europæisk retssagsførelse om migration, strafferetspleje, 'had', medier og civilt 'resilience' — det sidste betyder ofte resilience mod vælgeren. George Soros som folkedjævel er en anden, værre fil, og dette atlas kører den ikke. En fond, der bruger i kontinental skala på en postnational retsorden, er en aktør. Læs tilskuddene. Læs ikke memes.",
    interests: [
      "Et Europa, hvor nationale flertal ikke kan lukke døren eller debatten",
      "Strategisk retssagsførelse som politik",
      "Et civilsamfundslag uafhængigt af — og ofte fjendtligt over for — valgt begrænsning",
    ],
    methods: ["Tilskud", "Retssagsvehikler", "Medie- og universitetsprogrammer", "Netværket 'ekspert'-forsyning"],
    theaters: ["legal-europe", "brussels", "campus", "newsroom"],
    domains: ["ngo", "lawfare", "migration", "university", "taboo"],
  },
  {
    id: "psb-complex",
    name: "Public service-broadcastere",
    short: "BBC, DR, SVT, NRK, ARD/ZDF, France Télévisions, RTÉ",
    kind: "media",
    aliases: ["PSB", "licensfinansierede broadcastere", "public service-medier"],
    summary:
      "De vigtigste medieaktører i Nordeuropa, fordi de er dem, en vælger ikke kan slukke uden en politisk kamp. Deres charters siger informere, uddanne, underholde og holde magten til ansvar. Deres rekruttering siger de samme universiteter som ministeriet. Bias-studier, ombudsmandsrækker og migrationsfilen 2015–24 (hvem blev interviewet, hvilke tal var 'kontekst') er den åbne sag. En PSB er ikke en partikanal. Det er et vejrsystem.",
    interests: [
      "Beskytte licens- eller statstilskudsaftalen",
      "Forblive det moralske centrum mod 'polarisering'",
      "Behandle restriktionistisk politik som et problem, der skal forklares, ikke et publikum, der skal betjenes",
    ],
    methods: ["Rækkefølge", "Stilvejledninger", "Ekspert-rolodex", "Interne værdiregimer", "Krise-liturgi efter angreb"],
    theaters: ["newsroom", "scandinavia", "british-isles", "germany", "france"],
    domains: ["media", "public-service", "taboo"],
  },
  {
    id: "university-admin",
    name: "Universiteternes administrative kompleks",
    short: "DEI-kontorer, talekoder, fabrikken til næste ministerium",
    kind: "institution",
    aliases: ["campus-DEI", "ligestillingskontorer", "administrationen"],
    summary:
      "Magten på campus er ikke den berømte professor. Det er kontoret, der godkender ansættelser, arrangementer, forskningsetik og studentersanktioner. Det kontor taler et sprog importeret fra amerikansk HR og postkolonialt pensum, så eksporteret ind i europæiske embedsværk af de mennesker, det mønter. Udenlandske gaver (Qatar og andre) køber programmer; administrationen køber fred. Efter 7. oktober 2023 var produktet synligt på plænen.",
    interests: ["Administrativ vækst", "Risiko-off fred med aktivistiske studerende", "Et moralsk monopol på 'inklusion'"],
    methods: ["Talekoder", "Ansættelsesfiltre", "Arrangementsvetoer", "Bias-response-teams", "Partnerskab med islamistiske og identitære studenterorganisationer"],
    theaters: ["campus", "british-isles", "france", "germany"],
    domains: ["university", "taboo", "islamist-entry"],
  },
  {
    id: "ngo-litigation",
    name: "Retssags- og modtagelses-NGO'er",
    short: "ECRE, retshjælpsbutikker, SAR-NGO'er, det andet embedsværk",
    kind: "network",
    aliases: ["ECRE-kredsen", "SAR-NGO'er", "strategisk retssagsførelse", "flygtningeindustrielt kompleks"],
    summary:
      "Et marked og et præsteskab. Modtageentreprenører betales per ankomst. Retshjælps-NGO'er betales for at sagsøge den stat, der også finansierer dem. Sørednings-NGO'er skaber en våd korridor, hvis eksistens så citeres som bevis for, at korridoren ikke kan lukkes. ECRE og fætre koordinerer den juridiske linje på tværs af hovedstæder. Dette er ikke 'civilsamfund' som kontrol. Det er et operationslag med en forretningsmodel.",
    interests: ["Volumen, fordi volumen er budget og mening", "En retsorden, hvor håndhævelse ser ud som en krænkelse", "Moralsk standing mod valgt begrænsning"],
    methods: ["Både og busser", "Strasbourg-ansøgninger", "Mediepakning", "Kommissions- og fondstilskud"],
    theaters: ["mediterranean", "legal-europe", "brussels", "newsroom"],
    domains: ["ngo", "migration", "lawfare", "media"],
  },
  {
    id: "islamist-street",
    name: "Islamistisk gade og klanhåndhævelse",
    short: "Den udenretslige blasfemilov og no-go-kendsgerningen",
    kind: "movement",
    aliases: ["salafistiske miljøer", "klannetværk", "grooming-bande-mønsteret", "banlieue-gaden"],
    summary:
      "Ikke en enkelt organisation. En tilbagevendende kapacitet: straffe tegnere og lærere, politiere kvinder, køre seksuelle udnyttelsesnetværk, som embedsmænd var bange for at navngive, og hæve prisen på almindeligt politi, indtil staten forhandler. Van Gogh, Hebdo, Paty, optøjerne 2023, Rotherham og søstersagerne, svenske bombninger — forskellige mænd, samme lektie. Den hybride brug er nedstrøms: hver episode træner PSB og ministeriet til at tale om samhørighed snarere end den muliggørende bosættelse.",
    interests: ["Straffrihed i territorium", "Blasfemihåndhævelse", "Status inde i parallelsamfundet"],
    methods: ["Optøjer", "Målrettede drab og trusler", "Grooming og klankriminalitet", "Kommunal blok som politisk skjold"],
    theaters: ["france", "british-isles", "scandinavia", "low-countries", "germany"],
    domains: ["street", "islamist-entry", "taboo"],
  },
  {
    id: "salafi-milieu",
    name: "Det europæiske salafistmilieu",
    short: "Quietist på brochuren, et rejsebureau i køkkenet",
    kind: "movement",
    aliases: ["salafistnetværk", "Grimhøj-banen", "Maskinhusets fætre", "purist-jihadist-rørledningen"],
    summary:
      "Ikke et parti og ikke hvert skægget rum. En strøm: skriftpurisme, der isolerer flokken fra demos, og så — i den jihadistiske gren — sælger lejren. Grimhøj i Aarhus er det danske fotografi: en isfabrik, politiet knyttede til omkring en femtedel af landets Syriensrejsende. Minbaren nægter. Rejsen gjorde ikke. Franske, østrigske og tyske tjenester vil sige 'salafist' offentligt. Danmark foretrækker stadig 'radikalisering' som et socialt substansiv. Den hybride brug er poolen: et sakralt netværk, der kan være sogn om fredagen og rekrutteringsbutik om tirsdagen uden at skifte låsen.",
    interests: [
      "En flok, der svarer til en transnational umma før en dansk demos",
      "En rørledning til teatre — Syrien i går, hvor mærket er i morgen",
      "Straffrihed for rummet: nægt minbaren, behold køkkenet",
    ],
    methods: ["Studiekredse", "Isolation og takfir-lite", "Krypterede flyers", "Moské-nære rejsebureauer", "Veteranstjerne"],
    theaters: ["scandinavia", "france", "germany", "low-countries", "british-isles", "online"],
    domains: ["islamist-entry", "street", "taboo"],
  },
  {
    id: "hizb-ut-tahrir",
    name: "Hizb ut-Tahrir",
    short: "Åben kalifatpolitik fra en lovlig dansk moské",
    kind: "movement",
    aliases: ["HuT", "Masjid al-Faruq", "Befrielsespartiet"],
    summary:
      "Et transnationalt islamistisk parti, der vil have et kalifat og siger det på et københavnsk fortov. Tyskland har forbudt det. Danmark har ikke. Kühles kortlægning 2017 satte Masjid al-Faruq i de ni blandede og navngav den som Hizb ut-Tahrirs moské. Det er et dokumenteret rum, ikke et humør. Den hybride brug er lovlighed som dække: et parti sikkerhedstjenesterne holder øje med, der prædiker en politisk orden, Folketinget ikke må kalde en fjende uden at der skrives en ny forbrydelse mod navngivningen.",
    interests: [
      "Et kalifat som politisk program, ikke en metafor",
      "Holde det danske rum lovligt, mens det tyske ikke er",
      "Gøre enhver begrænsning til et ytringsfriheds-martyrium",
    ],
    methods: ["Offentlige demonstrationer", "Litteratur", "En navngivet moské", "Campus- og ungdomskredse"],
    theaters: ["scandinavia", "british-isles", "germany", "online"],
    domains: ["islamist-entry", "taboo", "street"],
  },
  {
    id: "russia",
    name: "Den Russiske Føderation",
    short: "En ægte gråzoneangriber — og en parasit på denne fil, ikke dens forfatter",
    kind: "state",
    aliases: ["Moskva", "Kreml", "RT / FIMI"],
    summary:
      "Det forrige atlas gjorde Rusland til principalen. Det var den primitive definition: kabler, GRU-brandstiftelse, hviderussiske grænsestunts, firehose-medier. De kampagner findes. De er ikke kampagnen, der omskrev Malmö, Molenbeek, Rotherham eller DSA. Moskvas interesse her er opportunistisk — forstærk bruddet, sælg 'dekadent Vesten', kør det lejlighedsvise grænsetrick. At behandle denne indre krig som en russisk op er selv et træk i tabudomænet. Optagelse er at holde parasitten på siden, ikke på tronen.",
    interests: [
      "Europæisk brud som et strategisk gode",
      "Migration som FIMI-tema og, ved det finske/norske hegn, som værktøj",
      "Omdirigere vestlig sikkerhedsenergi mod NATO-teatret og væk fra indre rekonstruktion",
    ],
    methods: ["FIMI", "Grænseinstrumentalisering med Hviderusland", "Lejlighedsvis dyrkning af både identitære og antirasistiske nyttige stemmer"],
    theaters: ["online", "scandinavia", "newsroom"],
    domains: ["taboo", "media", "migration"],
  },
  {
    id: "denmark-state",
    name: "Det danske restriktionistiske skift",
    short: "Det europæiske bevis for, at politik, ikke vejr, sætter tallene",
    kind: "state",
    aliases: ["paradigmeskiftet", "ghetto-/parallelsamfundslovene", "danske socialdemokrater efter 2019"],
    summary:
      "Ikke en fjende af dette atlas — en kontrolcase. Fra 2015–19 flyttede Danmark, under først en borgerlig og så en socialdemokratisk regering, til et 'paradigmeskifte': midlertidig beskyttelse, hjemsendelse, smykkeloven som teater, ghetto-/parallelsamfundslovgivning, en hård linje på syriske inddragelser og et offentligt argument om, at velfærdsstaten er offeret for volumen. Domstole og FN-organer har kæmpet stykker af det. Tallene flyttede sig. Det er derfor, landet hades i NGO-laget og studeres alle andre steder.",
    interests: [
      "En velfærdsstat, der forbliver en velfærdsstat",
      "Hjemsendelse som default, ikke integration-som-eufemisme",
      "Et offentligt sprog, hvori problemet må navngives",
    ],
    methods: ["Lov", "Ghetto-/parallelsamfundspakker", "Diplomatiske kampe i Strasbourg og Genève", "Socialdemokratisk omvendelse som politisk dække"],
    theaters: ["scandinavia", "legal-europe", "brussels"],
    domains: ["migration", "lawfare", "public-service", "supranational"],
  },
  {
    id: "pet-fe",
    name: "PET og FE",
    short: "Dansk efterretning: butikken, der kortlagde Syrien-rørledningen og så mistede retten til at tie",
    kind: "institution",
    aliases: [
      "Politiets Efterretningstjeneste",
      "Forsvarets Efterretningstjeneste",
      "det danske efterretningsmiljø",
      "Samsam",
      "Ahmed Samsam",
    ],
    summary:
      "En lille stats øjne. PET tager det indre: terror, ekstremisme, kontraspionage. FE tager det ydre: fremmedkrigere, partnertjenester, kablet. De rekrutterede Ahmed Samsam, betalte ham, sendte ham ind i Syrien 2013–14 og hverken-be-eller-afkræftede ham ind i en otteårig spansk terrordom. Højesteret i september 2025 tvang dem til at sige kildeforholdet højt. Optagelse her er ikke en dom om, at tjenesterne er fjenden. Det er protokollen over et HUMINT-kollaps i den ene europæiske kontrolcase, der ellers flyttede tallene.",
    interests: [
      "Holde kildeforhold ude af det offentlige register",
      "Kortlægge danske rejsende ind i jihadistgrupper uden at brænde kortlæggeren",
      "Overleve tilsyn, domstole og en presse, der behandler tavshed som skandalen",
    ],
    methods: [
      "Menneskelige kilder betalt i kontanter og udstyr",
      "Hverken be- eller afkræft som doktrin",
      "Tjeneste-til-tjeneste-noter, der aldrig bliver retsbevis",
      "Kompensationssamtaler i et lukket rum, mens den offentlige linje er tavshed",
    ],
    theaters: ["scandinavia", "legal-europe", "newsroom"],
    domains: ["islamist-entry", "lawfare", "taboo", "public-service", "street"],
  },
];

export const actorById = Object.fromEntries(actors.map((a) => [a.id, a])) as Record<string, Actor>;
