import type { TimelineEvent } from "./types";

export const timeline: TimelineEvent[] = [
  {
    id: "t-1968",
    date: "1968",
    title: "Den lange march navngiver sig selv",
    attribution: "confirmed",
    domainId: "university",
    theaterId: "campus",
    note: "Nyvenstreintellektuelle beskriver erobring af skole, presse og administration som arbejdet. En metode, ikke et skældsord. Fabrikken åbner.",
  },
  {
    id: "t-1991-memo",
    date: "1991-05",
    title: "Broderskabets forklaringsmemorandum",
    campaignId: "brotherhood-settlement",
    domainId: "islamist-entry",
    attribution: "high",
    note: "Bosættelse som en 'civilisations-jihadistisk proces.' Amerikansk retssagsbilag, ikke en europæisk ordre — og ikke en forfalskning.",
  },
  {
    id: "t-1999-oic",
    date: "1999",
    title: "OIC's spor om 'religiøs bagtalelse' begynder for alvor",
    campaignId: "oic-islamophobia",
    domainId: "lawfare",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Blasfemi på jagt efter et menneskerettighedskostume.",
  },
  {
    id: "t-2004-vangogh",
    date: "2004-11-02",
    title: "Theo van Gogh myrdet i Amsterdam",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "low-countries",
    attribution: "confirmed",
    note: "Filminstruktøren som mål. Fortuyn allerede død. Tidlig advarsel straffet.",
  },
  {
    id: "t-2005-cartoons",
    date: "2005-09",
    title: "Jyllands-Postens tegninger",
    campaignId: "oic-islamophobia",
    domainId: "taboo",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "En dansk presshistorie bliver et diplomatisk system. Undervisningscasen.",
  },
  {
    id: "t-2005-banlieue",
    date: "2005-10",
    title: "Franske banlieue-optøjer",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "france",
    attribution: "high",
    note: "Gadetaksten på almindeligt politi, allerede et landskab.",
  },
  {
    id: "t-2011-istanbul",
    date: "2011-07",
    title: "Istanbul-processen lanceret",
    campaignId: "oic-islamophobia",
    domainId: "supranational",
    attribution: "confirmed",
    note: "Implementering af HRC 16/18. Vestlige diplomater tror, de kompromitterede. OIC er ikke færdig.",
  },
  {
    id: "t-2011-breivik",
    date: "2011-07-22",
    title: "Utøya og Oslo — tabuets kill-switch",
    campaignId: "taboo-naming",
    domainId: "taboo",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Et monster, der citerede udskiftning. Han ejer ikke fertilitetsrater. Tabuet holder ham alligevel på skrivebordet.",
  },
  {
    id: "t-2014-rotherham",
    date: "2014-08",
    title: "Jay-rapporten om Rotherham",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "british-isles",
    attribution: "confirmed",
    note: "Officiel kujoneri med et racetabu i centrum. Regningen var piger.",
  },
  {
    id: "t-2015-hebdo",
    date: "2015-01-07",
    title: "Charlie Hebdo",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "france",
    attribution: "confirmed",
    note: "Redaktionen som mål. Samhørighedsliturgi mod en civilisatorisk kendsgerning.",
  },
  {
    id: "t-2015-merkel",
    date: "2015-09",
    title: "Merkels Öffnung",
    campaignId: "mass-settlement",
    domainId: "migration",
    theaterId: "germany",
    attribution: "confirmed",
    note: "Den største enkelte elitebeslutning i den indre krig. Ikke en vejrbegivenhed.",
  },
  {
    id: "t-2015-bataclan",
    date: "2015-11-13",
    title: "Bataclan og angrebene 13. november",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "france",
    attribution: "confirmed",
    note: "Koncertsalen. Ikke en taleforbrydelse — klimaet, hvori taleforbrydelser derefter skrives.",
  },
  {
    id: "t-2015-cologne",
    date: "2015-12-31",
    title: "Nytår i Köln",
    campaignId: "psb-monopoly",
    domainId: "media",
    theaterId: "germany",
    attribution: "high",
    note: "Kriminalitet plus en stilvejledningskrise. Oprindelse som det usigelige.",
  },
  {
    id: "t-2016-hatecode",
    date: "2016",
    title: "EU's adfærdskodeks om ulovlig hadtale",
    campaignId: "counter-legislation",
    domainId: "lawfare",
    theaterId: "brussels",
    attribution: "confirmed",
    note: "Det frivillige frø til den senere DSA-maskine.",
  },
  {
    id: "t-2018-gcm",
    date: "2018-12-19",
    title: "Den globale kompakt for migration vedtaget",
    campaignId: "global-compact",
    domainId: "migration",
    attribution: "confirmed",
    note: "Ikke-bindende, og et script. Narrativ-forandring-bureaukratierne tager over herfra.",
  },
  {
    id: "t-2019-denmark",
    date: "2019",
    title: "Dansk paradigmeskifte under socialdemokraterne",
    campaignId: "denmark-reversal",
    domainId: "migration",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Kontrolcasen: omvend partiet, der ejer bygningen.",
  },
  {
    id: "t-2020-paty",
    date: "2020-10-16",
    title: "Samuel Paty halshugget",
    campaignId: "blasphemy-enforcement",
    domainId: "street",
    theaterId: "france",
    attribution: "confirmed",
    note: "Skolen som mål. Kampagnen mod læreren, fuldført.",
  },
  {
    id: "t-2021-scotland",
    date: "2021-04",
    title: "Skotlands Hate Crime Act",
    campaignId: "counter-legislation",
    domainId: "lawfare",
    theaterId: "british-isles",
    attribution: "confirmed",
    note: "Ophidselsesforbrydelser udvidet. Den bizarre rekursion, i lov.",
  },
  {
    id: "t-2021-ma-denmark",
    date: "2021",
    title: "M.A. mod Danmark — ventetider for familiesammenføring",
    campaignId: "ecthr-lock",
    domainId: "supranational",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Strasbourg mod kontrolcasen.",
  },
  {
    id: "t-2022-rwanda",
    date: "2022-06-14",
    title: "EMD regel 39 tømmer den første Rwanda-flyvning",
    campaignId: "ecthr-lock",
    domainId: "supranational",
    theaterId: "british-isles",
    attribution: "confirmed",
    note: "Fotografiet af låsen. Ikke EU. Konventionen.",
  },
  {
    id: "t-2023-nahel",
    date: "2023-06",
    title: "Nahel-optøjerne i Frankrig",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "france",
    attribution: "high",
    note: "En uge af brændt Frankrig som politisk takst.",
  },
  {
    id: "t-2023-oct7-campus",
    date: "2023-10",
    title: "Campus efter 7. oktober",
    campaignId: "university-capture",
    domainId: "university",
    theaterId: "campus",
    attribution: "high",
    note: "Fabrikkens produkt, udstillet. Qatar, Broderskabets ungdom, administration — én produktionslinje.",
  },
  {
    id: "t-2024-dsa",
    date: "2024-02",
    title: "Digital Services Act fuldt gældende",
    campaignId: "dsa-speech",
    domainId: "lawfare",
    theaterId: "online",
    attribution: "confirmed",
    note: "Det nye knudepunkt, live.",
  },
  {
    id: "t-2024-twotier",
    date: "2024-08",
    title: "Britisk two-tier bliver et husstandsord",
    campaignId: "two-tier",
    domainId: "street",
    theaterId: "british-isles",
    attribution: "high",
    note: "Southport-optøjer og sigtelsesoptik. Masseopfattelse som strategisk kendsgerning.",
  },
  {
    id: "t-2025-codes",
    date: "2025-02",
    title: "Hadtale- og desinfokoder boltet på DSA",
    campaignId: "dsa-speech",
    domainId: "lawfare",
    theaterId: "brussels",
    attribution: "confirmed",
    note: "Frivillige, så reviderbare. Platforme som et kontinentalt talehåndtag.",
  },
  {
    id: "t-2025-oic",
    date: "2025-06",
    title: "OIC CFM stadig optaget af skandinaviske koranafbrændinger",
    campaignId: "oic-islamophobia",
    domainId: "lawfare",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Istanbul-processen skal 'genoplives.' Små stater, lang hukommelse, levende sag.",
  },
  {
    id: "t-2026-hubs",
    date: "2026-08",
    title: "Danskledet returhub-diplomati i Kigali",
    campaignId: "denmark-reversal",
    domainId: "migration",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Danmark, Tyskland, Østrig, Grækenland, Nederlandene. Workarundet, eksporteret — og allerede et lovkrigsmål.",
  },
  {
    id: "t-1967-nusrat",
    date: "1967-07-21",
    title: "Første egentlige moské i Norden",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Nusrat Jahan, Hvidovre. Ahmadiyya. Aviserne var nysgerrige. Folketinget var ikke.",
  },
  {
    id: "t-1974-sunni",
    date: "1974",
    title: "Én sunnimoské i levende erindring",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Kontrolåret. Gæstearbejdernes rum kun ved at begynde. Ahmadiyya erklæret uden for islam samme år.",
  },
  {
    id: "t-2006-kuehle",
    date: "2006",
    title: "Første nationale moskékortlægning: ~115",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Kühles walk-in. 104 sunni, 10 shia, 1 Ahmadiyya. Det kortlagte lag får et tal.",
  },
  {
    id: "t-2012-emir",
    date: "2012-11",
    title: "Danske emir-videoer sælger Syrien-lejren",
    campaignId: "syria-pipeline",
    domainId: "islamist-entry",
    theaterId: "online",
    attribution: "confirmed",
    note: "Krigen bliver et indenlandsk ungdomsprodukt. Annoncen er aggressiv.",
  },
  {
    id: "t-2014-hbku",
    date: "2014-06",
    title: "Qatars stormoské åbner på Rovsingsgade",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Hamad Bin Khalifa Civilisation Center. Det nybyggede lag får sit fotografi. Et fremmed sogn i hovedstaden.",
  },
  {
    id: "t-2014-grimhoj",
    date: "2014",
    title: "Grimhøj navngivet som rejsebureau",
    campaignId: "syria-pipeline",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Politi: omkring en femtedel af de danske Syriensrejsende. Isfabrikken som butiksvindue.",
  },
  {
    id: "t-2015-imam-ali",
    date: "2015",
    title: "Imam Ali-moskéen åbner på Vibevej",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Iransk sogn. Folketinget opdager senere, at rummet ikke kan opløses.",
  },
  {
    id: "t-2016-pet135",
    date: "2016-04",
    title: "PET: 135+ danske rejsende til Syrien/Irak",
    campaignId: "syria-pipeline",
    domainId: "street",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Blandt de højeste per capita i EU. Rørledningen er ikke længere nægtelig.",
  },
  {
    id: "t-2017-kuehle2",
    date: "2017-12",
    title: "Kortlagte moskéer ~170, +48% på elleve år",
    campaignId: "mosque-census",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Kühle & Larsen. ~40% transnationale. Mindst ti ucertificerede. Mørketallet begynder at tale.",
  },
  {
    id: "t-2025-hidayyah",
    date: "2026-03",
    title: "Blodpengemoskéen beholder anerkendelsen",
    campaignId: "mosque-census",
    domainId: "street",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Al-Hidayyah: mægling efter klanmord, derefter ingen sanktion. Et fjendtligt rum som rettighedshaver.",
  },
  {
    id: "t-2012-samsam",
    date: "2012",
    title: "PET rekrutterer Ahmed Samsam som betalt Syrien-kilde",
    campaignId: "samsam-case",
    domainId: "islamist-entry",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "Bandefortid, syrisk baggrund, dansk pas. Butikkens vej ind i en rørledning, den ikke selv kan gå.",
  },
  {
    id: "t-2017-samsam-spain",
    date: "2017-06",
    title: "Samsam anholdt i Spanien — Københavns linje er tavshed",
    campaignId: "samsam-case",
    domainId: "lawfare",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Hverken be- eller afkræft. Spanien dømmer ham i 2018 for at have tilsluttet sig Islamisk Stat. Otte år.",
  },
  {
    id: "t-2021-samsam-memo",
    date: "2021-06",
    title: "Lækket PET-notat: alvorligt svigt, enestående adgang, ingen redning",
    campaignId: "samsam-case",
    domainId: "taboo",
    theaterId: "newsroom",
    attribution: "high",
    note: "Tjenestens eget papir. Kompensation talt. Han sidder stadig.",
  },
  {
    id: "t-2021-findsen-sweep",
    date: "2021-12-08",
    title: "PET anholder FE-chefen og Samsams kildefører i ét hug",
    campaignId: "samsam-case",
    domainId: "public-service",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Efterretning i krig med sig selv. Samsam-lækket er en af strengene. Findsens sigtelser falder senere.",
  },
  {
    id: "t-2025-samsam-sc",
    date: "2025-09-02",
    title: "Højesteret tvinger PET og FE til at anerkende Samsam",
    campaignId: "samsam-case",
    domainId: "lawfare",
    theaterId: "legal-europe",
    attribution: "confirmed",
    note: "Syv dommere, enstemmigt. Fælles udtalelse samme eftermiddag. NCND viger. Enhver fremtidig kilde kan læse det.",
  },
  {
    id: "t-2018-medieaftale",
    date: "2018-06",
    title: "VLAK/DF-medieaftale forsøger at binde DR",
    campaignId: "medieforlig-neutrality",
    domainId: "public-service",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "20% cut, ingen lange netartikler. Sidste højre-binding. Rullet tilbage inden et år som 'armslængde.'",
  },
  {
    id: "t-2023-medieaftale",
    date: "2023-06-14",
    title: "Medieaftale 2023–26: pluralisme bliver den målrettede pligt",
    campaignId: "medieforlig-neutrality",
    domainId: "media",
    theaterId: "scandinavia",
    attribution: "confirmed",
    note: "'Alsidighed og pluralisme' som opgave. 'Upartisk' bliver som sætning. Diversitet bliver tællelig.",
  },
  {
    id: "t-2026-medieprogram",
    date: "2026-06",
    title: "S–SF–RV–M-program: slank DR's ramme, auditér ikke politikken",
    campaignId: "medieforlig-neutrality",
    domainId: "public-service",
    theaterId: "scandinavia",
    attribution: "high",
    note: "Afbureaukratisering som arbejdstitel. 2025-slagsidetilbuddet står ikke i programmet.",
  },
];
