/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CensusRouteImport } from './routes/census'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as MethodRouteImport } from './routes/method'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ActorsIndexRouteImport } from './routes/actors/index'
import { Route as ActorsActorIdRouteImport } from './routes/actors/$actorId'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as DomainsDomainIdRouteImport } from './routes/domains/$domainId'
import { Route as TheatersIndexRouteImport } from './routes/theaters/index'
import { Route as TheatersTheaterIdRouteImport } from './routes/theaters/$theaterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CensusRoute = CensusRouteImport.update({
  id: '/census',
  path: '/census',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIndexRoute = ActorsIndexRouteImport.update({
  id: '/actors/',
  path: '/actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsActorIdRoute = ActorsActorIdRouteImport.update({
  id: '/actors/$actorId',
  path: '/actors/$actorId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsDomainIdRoute = DomainsDomainIdRouteImport.update({
  id: '/domains/$domainId',
  path: '/domains/$domainId',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersIndexRoute = TheatersIndexRouteImport.update({
  id: '/theaters/',
  path: '/theaters/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersTheaterIdRoute = TheatersTheaterIdRouteImport.update({
  id: '/theaters/$theaterId',
  path: '/theaters/$theaterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/census': typeof CensusRoute
  '/doctrine': typeof DoctrineRoute
  '/method': typeof MethodRoute
  '/timeline': typeof TimelineRoute
  '/actors/$actorId': typeof ActorsActorIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/domains/$domainId': typeof DomainsDomainIdRoute
  '/theaters/$theaterId': typeof TheatersTheaterIdRoute
  '/actors/': typeof ActorsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/theaters/': typeof TheatersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/census': typeof CensusRoute
  '/doctrine': typeof DoctrineRoute
  '/method': typeof MethodRoute
  '/timeline': typeof TimelineRoute
  '/actors/$actorId': typeof ActorsActorIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/domains/$domainId': typeof DomainsDomainIdRoute
  '/theaters/$theaterId': typeof TheatersTheaterIdRoute
  '/actors': typeof ActorsIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/theaters': typeof TheatersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/census': typeof CensusRoute
  '/doctrine': typeof DoctrineRoute
  '/method': typeof MethodRoute
  '/timeline': typeof TimelineRoute
  '/actors/$actorId': typeof ActorsActorIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/domains/$domainId': typeof DomainsDomainIdRoute
  '/theaters/$theaterId': typeof TheatersTheaterIdRoute
  '/actors/': typeof ActorsIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/theaters/': typeof TheatersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/census'
    | '/doctrine'
    | '/method'
    | '/timeline'
    | '/actors/$actorId'
    | '/campaigns/$campaignId'
    | '/domains/$domainId'
    | '/theaters/$theaterId'
    | '/actors/'
    | '/campaigns/'
    | '/domains/'
    | '/theaters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/census'
    | '/doctrine'
    | '/method'
    | '/timeline'
    | '/actors/$actorId'
    | '/campaigns/$campaignId'
    | '/domains/$domainId'
    | '/theaters/$theaterId'
    | '/actors'
    | '/campaigns'
    | '/domains'
    | '/theaters'
  id:
    | '__root__'
    | '/'
    | '/census'
    | '/doctrine'
    | '/method'
    | '/timeline'
    | '/actors/$actorId'
    | '/campaigns/$campaignId'
    | '/domains/$domainId'
    | '/theaters/$theaterId'
    | '/actors/'
    | '/campaigns/'
    | '/domains/'
    | '/theaters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CensusRoute: typeof CensusRoute
  DoctrineRoute: typeof DoctrineRoute
  MethodRoute: typeof MethodRoute
  TimelineRoute: typeof TimelineRoute
  ActorsActorIdRoute: typeof ActorsActorIdRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  DomainsDomainIdRoute: typeof DomainsDomainIdRoute
  TheatersTheaterIdRoute: typeof TheatersTheaterIdRoute
  ActorsIndexRoute: typeof ActorsIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  TheatersIndexRoute: typeof TheatersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/census': {
      id: '/census'
      path: '/census'
      fullPath: '/census'
      preLoaderRoute: typeof CensusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/': {
      id: '/actors/'
      path: '/actors'
      fullPath: '/actors/'
      preLoaderRoute: typeof ActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$actorId': {
      id: '/actors/$actorId'
      path: '/actors/$actorId'
      fullPath: '/actors/$actorId'
      preLoaderRoute: typeof ActorsActorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId': {
      id: '/domains/$domainId'
      path: '/domains/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof DomainsDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/': {
      id: '/theaters/'
      path: '/theaters'
      fullPath: '/theaters/'
      preLoaderRoute: typeof TheatersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/$theaterId': {
      id: '/theaters/$theaterId'
      path: '/theaters/$theaterId'
      fullPath: '/theaters/$theaterId'
      preLoaderRoute: typeof TheatersTheaterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CensusRoute: CensusRoute,
  DoctrineRoute: DoctrineRoute,
  MethodRoute: MethodRoute,
  TimelineRoute: TimelineRoute,
  ActorsActorIdRoute: ActorsActorIdRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  DomainsDomainIdRoute: DomainsDomainIdRoute,
  TheatersTheaterIdRoute: TheatersTheaterIdRoute,
  ActorsIndexRoute: ActorsIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  TheatersIndexRoute: TheatersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
